# CMake generated Testfile for 
# Source directory: /home/zoe/CLionProjects/leveldb
# Build directory: /home/zoe/CLionProjects/leveldb
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/home/zoe/CLionProjects/leveldb/c_test")
set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;339;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(fault_injection_test "/home/zoe/CLionProjects/leveldb/fault_injection_test")
set_tests_properties(fault_injection_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;340;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(issue178_test "/home/zoe/CLionProjects/leveldb/issue178_test")
set_tests_properties(issue178_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;342;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(issue200_test "/home/zoe/CLionProjects/leveldb/issue200_test")
set_tests_properties(issue200_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;343;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(issue320_test "/home/zoe/CLionProjects/leveldb/issue320_test")
set_tests_properties(issue320_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;344;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(env_test "/home/zoe/CLionProjects/leveldb/env_test")
set_tests_properties(env_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;346;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(status_test "/home/zoe/CLionProjects/leveldb/status_test")
set_tests_properties(status_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;347;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(no_destructor_test "/home/zoe/CLionProjects/leveldb/no_destructor_test")
set_tests_properties(no_destructor_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;348;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(autocompact_test "/home/zoe/CLionProjects/leveldb/autocompact_test")
set_tests_properties(autocompact_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;351;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(corruption_test "/home/zoe/CLionProjects/leveldb/corruption_test")
set_tests_properties(corruption_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;352;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(db_test "/home/zoe/CLionProjects/leveldb/db_test")
set_tests_properties(db_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;353;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(dbformat_test "/home/zoe/CLionProjects/leveldb/dbformat_test")
set_tests_properties(dbformat_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;354;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(filename_test "/home/zoe/CLionProjects/leveldb/filename_test")
set_tests_properties(filename_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;355;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(log_test "/home/zoe/CLionProjects/leveldb/log_test")
set_tests_properties(log_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;356;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(recovery_test "/home/zoe/CLionProjects/leveldb/recovery_test")
set_tests_properties(recovery_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;357;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(skiplist_test "/home/zoe/CLionProjects/leveldb/skiplist_test")
set_tests_properties(skiplist_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;358;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(version_edit_test "/home/zoe/CLionProjects/leveldb/version_edit_test")
set_tests_properties(version_edit_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;359;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(version_set_test "/home/zoe/CLionProjects/leveldb/version_set_test")
set_tests_properties(version_set_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;360;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(write_batch_test "/home/zoe/CLionProjects/leveldb/write_batch_test")
set_tests_properties(write_batch_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;361;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(memenv_test "/home/zoe/CLionProjects/leveldb/memenv_test")
set_tests_properties(memenv_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;363;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(filter_block_test "/home/zoe/CLionProjects/leveldb/filter_block_test")
set_tests_properties(filter_block_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;365;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(table_test "/home/zoe/CLionProjects/leveldb/table_test")
set_tests_properties(table_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;366;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(arena_test "/home/zoe/CLionProjects/leveldb/arena_test")
set_tests_properties(arena_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;368;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(bloom_test "/home/zoe/CLionProjects/leveldb/bloom_test")
set_tests_properties(bloom_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;369;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(cache_test "/home/zoe/CLionProjects/leveldb/cache_test")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;370;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(coding_test "/home/zoe/CLionProjects/leveldb/coding_test")
set_tests_properties(coding_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;371;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(crc32c_test "/home/zoe/CLionProjects/leveldb/crc32c_test")
set_tests_properties(crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;372;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(hash_test "/home/zoe/CLionProjects/leveldb/hash_test")
set_tests_properties(hash_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;373;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(logging_test "/home/zoe/CLionProjects/leveldb/logging_test")
set_tests_properties(logging_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;374;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
add_test(env_posix_test "/home/zoe/CLionProjects/leveldb/env_posix_test")
set_tests_properties(env_posix_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zoe/CLionProjects/leveldb/CMakeLists.txt;336;add_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;381;leveldb_test;/home/zoe/CLionProjects/leveldb/CMakeLists.txt;0;")
subdirs("third_party/googletest")
